name: Sync Beginner Tags

on:
  issues:
    types: [labeled]

permissions: {}

jobs:
  sync_beginner_tags:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: github.event.label.name == 'level:beginner'
    steps:
      - name: Add associated tags
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['good first issue', 'beginner friendly']
            });
